import org.gradle.kotlin.dsl.support.listFilesOrdered
/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.14.2/userguide/multi_project_builds.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */
listOf(
    "applications",
    "components",
    "features",
).onEach { projCollection ->
    when (projCollection) {
        "features" -> file(projCollection).listFilesOrdered { it.isDirectory and it.name.startsWith("_").not() }
            .onEach { feature ->
                feature.listFilesOrdered { it.isDirectory and it.name.startsWith("_").not() }.onEach { featComponent ->
                    include(":$projCollection:${feature.name}:${featComponent.name}")
                }
            }

        else -> file(projCollection).listFilesOrdered { it.isDirectory and it.name.startsWith("_").not() }
            .onEach { subProj ->
                include(":$projCollection:${subProj.name}")
            }
    }
}
rootProject.name = "kmp-structure"
